#!/usr/bin/env python
"""
Make requests to the TrustYou connect service

This script is an example of client-side code that synchronizes the session of
a user within the TrustYou system, allowing the external user to log into TrustYou.
"""
import argparse
import urllib
# These modules are used in the commented sections.
# import random
# import string
# import time

from oauthlib import oauth1
from requests import put


def parse_args():
    parser = argparse.ArgumentParser('Create signed SSO request for TY Connect')
    parser.add_argument(
        'rsa_private_key',
        type=lambda path: open(path).read(),
        help="Your private key's file path"
    )
    parser.add_argument('partner_id', )


def generate_signed_request(partner_id, hotel_id, private_key, connect_url):
    # At this moment we don't accept multiple query sting parameters,
    # so a dict can be used.
    params = {
        'partner_id': partner_id,           # partner_id must be identical to oauth_token
        'oauth_token': hotel_id,

        # These 4 mandatory parameters are generated by the oauth1.Client during the signing
        # process already, so they will be automatically added.
        # They are only left here, as an example, if using another library instead of oauthlib.
        # 'oauth_consumer_key': partner_id,
        # 'oauth_timestamp': int(time.time()),
        # 'oauth_nonce': ''.join(random.choice(string.letters) for _ in range(15)),
        # 'oauth_signature_method': 'RSA-SHA1',
    }

    client = oauth1.Client(
        client_key=partner_id,   # this will be the value of 'oauth_token' in the signed url
        signature_method=oauth1.SIGNATURE_RSA,
        rsa_key=private_key,
        signature_type=oauth1.SIGNATURE_TYPE_QUERY
    )

    unsigned_url = connect_url + '?' + urllib.urlencode(params)

    url, headers, body = client.sign(unsigned_url, http_method='PUT')

    response = put(
        connect_url,
    )
